.TH BASHBUD 1 2019\-08\-13 Linx "User Manuals"
.SH NAME
.PP
\fB\fCbashbud\fR \- Generate documents and manage
projects

.SH SYNOPSIS
.PP
.RS

.nf
bashbud \-\-new|\-n    [GENERATOR] **TARGET\_DIR**
bashbud \-\-bump|\-b   [PROJECT\_DIR]
bashbud \-\-link|\-l [PROJECT\_DIR]
bashbud \-\-get|\-g KEY [PROJECT\_DIR]
bashbud \-\-set|\-s KEY VALUE [PROJECT\_DIR]
bashbud \-\-help|\-h
bashbud \-\-version|\-v

.fi
.RE

.SH DESCRIPTION
.PP
\fB\fCbashbud\fR can be used to quickly create new
scripts with cli\-option support and automatic
documentation applied.

.SH OPTIONS
.PP
\fB\fC\-\-new\fR|\fB\fC\-n\fR
.br
Creates a new project at TARGET\_DIR (\fIif
TARGET\_DIR doesnt exist, if it does script will
exit\fP), based on GENERATOR. If GENERATOR is
omitted the \fBdefault\fP generator will be used.
After all files are copied and linked, the project
is \fIbumped\fP (\fIsame as:\fP \fB\fCbashbud \-\-bump
TARGET\_DIR\fR).

.PP
\fB\fC\-\-bump\fR|\fB\fC\-b\fR
.br
The current working direcory will be set as
PROJECT\_DIR if none is specified. When a project
is \fIbumped\fP,  \fB\fCbashbud\fR will read the
\fImanifest.md\fP file in PROJECT\_DIR, (\fIor exit if no
manifest.md file exists\fP). If a generator \fBtype\fP
is specified in the \fBfront matter\fP  (the \fIYAML\fP
section starting the document) of the
\fImanifest.md\fP file, that generator will be used to
update the project based on the content of the
\fImanifest.md\fP file and the \fImanifest.d\fP directory
(\fIif it exists\fP). If a directory named \fIbashbud\fP
exists within \fIPROJECT\_DIR\fP, that directory will
be used as a generator.

.PP
\fB\fC\-\-link\fR|\fB\fC\-l\fR
.br
Add any missing links from the generators
\fB\fC\_\_link\fR directory, to \fB\fCPROJECT\_DIR\fR\&.

.PP
\fB\fC\-\-get\fR|\fB\fC\-g\fR KEY
.br
Get the value from a key in the YAML frontmatter
of the manifest.md. If last argument is a
directory, the manifest in that directory will be
used, otherwise the current directory is assumed.

.PP
\fB\fC\-\-set\fR|\fB\fC\-s\fR VALUE
.br
Set the value of KEY in the YAML frontmatter of
the manifest.md to VALUE. If last argument is a
directory, the manifest in that directory will be
used, otherwise the current directory is assumed.

.PP
\fB\fC\-\-help\fR|\fB\fC\-h\fR
.br
Show help and exit.

.PP
\fB\fC\-\-version\fR|\fB\fC\-v\fR
.br
Show version and exit.

.SH ENVIRONMENT
.PP
``
.br
bashbud config dir location. defaults to:
$XDG\_CONFIG\_HOME/bashbud

.SH DEPENDENCIES
.PP
 ``

.PP
budRich 
\[la]https://github.com/budlabs\[ra]

.SH SEE ALSO
.PP
bash(1), awk(1), sed(1),
